### PR TITLE
Update to 1.0.0

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Downloading and building the eigen library is dangerous - instead we should link to the corresponding conda package: @YuuuXie
```
-- Using src='https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz'
-- Using src='https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz'
 ```

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by YuuuXie** [comment]
> Downloading and building the eigen library is dangerous - instead we should link to the corresponding conda package: @YuuuXie
> 
> ```
> -- Using src='https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz'
> -- Using src='https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz'
> ```

Ah Ok I see, do I need to change the CMakeLists.txt of flare for your new push or you have found a way around?

**Comment by jan-janssen** [comment]
> Ah Ok I see, do I need to change the CMakeLists.txt of flare for your new push or you have found a way around?

Can you point me to the `CMakeLists.txt` file ?

**Comment by YuuuXie** [comment]
> > Ah Ok I see, do I need to change the CMakeLists.txt of flare for your new push or you have found a way around?
> 
> Can you point me to the `CMakeLists.txt` file ?

Sure. Since you are looking at the 1.0.0 version, here is the link: https://github.com/mir-group/flare/blob/1.0.0/CMakeLists.txt

You can let me know how you expect me to make any revision, or maybe you want to make a PR directly to the flare repo

**Comment by YuuuXie** [comment]
Hi @jan-janssen, since I saw that the "win" builds are failing, I think we can skip it because people in general won't run flare on windows. But if you can make it work it will still be great, just don't want to take you too much time if the win build is the black sheep

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@YuuuXie I managed to build the other versions: 

- https://github.com/conda-forge/mir-flare-feedstock/pull/18 
- https://github.com/conda-forge/mir-flare-feedstock/pull/19
- https://github.com/conda-forge/mir-flare-feedstock/pull/20

Still I am not very much an expert with `cmake` so it would be great if you can take a look at the linking and see if you can link the corresponding conda packages directly like `nlohmann_json`, `eigen` and `pybind11`.

**Comment by YuuuXie** [comment]
Hi @jan-janssen , this is super helpful, thank you so much! As for the cmake, I can revise the CMakeLists.txt file such that it can find Eigen json and pybind from `$CONDA_PREFIX`. I can try pushing the change, and then will need you to rebuild them?

Another questions is regarding the `mkl` linking, I see you are using liblapacke now, I wonder if it is not possible to link to mkl? If not using mkl, we also have a version using openblas, which needs
```
conda install libopenblas=*=*openmp* openblas
```
I'm wondering if you have any thoughts on this

**Comment by jan-janssen** [comment]
> I'm wondering if you have any thoughts on this

https://conda-forge.org/docs/maintainer/knowledge_base.html#blas

**Comment by YuuuXie** [comment]
Hi @jan-janssen , I just updated the 1.0.0 tag version, could you try rebuilding it? If it works, I will change the other versions as well. 

So in the meta.yaml, we will need to add `pybind11`, `eigen<3.4` and `nlohmann_json` to the requirements. thanks!

**Comment by jan-janssen** [comment]
It seems to be still downloading the source code: 
```
[ 10%] Performing download step (download, verify and extract) for 'eigen_project'
  -- Downloading...
     dst='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/pybind11_project-prefix/src/v2.3.0.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz'
  -- Downloading...
     dst='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/eigen_project-prefix/src/3.3.7.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz'
  -- verifying file...
         file='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/pybind11_project-prefix/src/v2.3.0.tar.gz'
  -- Downloading... done
  -- extracting...
       src='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/pybind11_project-prefix/src/v2.3.0.tar.gz'
       dst='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/External/pybind11'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  [ 12%] No update step for 'pybind11_project'
  [ 15%] No patch step for 'pybind11_project'
  [ 17%] No configure step for 'pybind11_project'
  [ 20%] No build step for 'pybind11_project'
  [ 23%] No install step for 'pybind11_project'
  [ 25%] Completed 'pybind11_project'
  [ 25%] Built target pybind11_project
  -- verifying file...
         file='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/eigen_project-prefix/src/3.3.7.tar.gz'
  -- Downloading... done
  -- extracting...
       src='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/eigen_project-prefix/src/3.3.7.tar.gz'
       dst='/home/conda/feedstock_root/build_artifacts/mir-flare_1667230852475/work/build/temp.linux-x86_64-cpython-39/External/Eigen3'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
```

**Comment by YuuuXie** [comment]
Hi @jan-janssen , do you know during the conda build, where are the packages installed? Because in my cmake setting, I utilize the `CONDA_PREFIX` environmental variable to point to the conda env directory, and find the package (headers) in its `include` folder. 

This works with direct cmake + make compilation. Basically, I do
```
conda activate myenv
conda install pybind11 eigen nlomann_json -c conda-forge
cmake ..
```
it just finds all the packages in the `CONDA_PREFIX` folder during `cmake`

I wonder if during the conda build, the `CONDA_PREFIX` is not set, or a different environmental variable needs to be set to locate the package?

**Comment by jan-janssen** [comment]
@YuuuXie Great work - Can you update the other tags correspondingly? Then we can continue releasing all versions on conda-froge.

**Comment by jan-janssen** [comment]
> I wonder if during the conda build, the `CONDA_PREFIX` is not set, or a different environmental variable needs to be set to locate the package?

It is a bit confusing, during the build process conda is looking for `PREFIX`, so I created the `cmake.patch` to fix this.

**Comment by YuuuXie** [comment]
> @YuuuXie Great work - Can you update the other tags correspondingly? Then we can continue releasing all versions on conda-froge.

Hi @jan-janssen, thank you so much for updating the files and releasing it! I saw that you have merged the other versions' PR as well. I think I can update the flare cmake file such that we can get around with the cmake.patch in the future release! Again, I really appreciate your help!

**Pull request merged**
