### PR TITLE
Debug 1.3.0

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
No matter if linking to `mkl` or `lapacke` the error remains the same: 
```
/home/conda/feedstock_root/build_artifacts/mir-flare_1667344455482/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/flare/bffs/sgp/sparse_gp.py:13: UserWarning: Cannot import _C_flare: ModuleNotFoundError: No module named 'flare.bffs.sgp._C_flare'
  warnings.warn(f"Cannot import _C_flare: {e.__class__.__name__}: {e}")
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mir-flare_1667344455482/test_tmp/run_test.py", line 5, in <module>
    import flare.bffs.sgp.lib_C_flare
ImportError: /home/conda/feedstock_root/build_artifacts/mir-flare_1667344455482/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/flare/bffs/sgp/lib_C_flare.so: undefined symbol: _ZTI6Kernel
Tests failed for mir-flare-1.3.0-py39hf939315_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by YuuuXie** [comment]
@jan-janssen I'm a bit worried that this `lib_C_flare.so` file is not linked to either mkl or lapacke at all. As I mentioned in the pull request #22 , when I tried to do `conda install mir-flare`, checking the compiled `lib_C_flare.so`, it does not show any linking to either openblas or openmp etc.
```
$ ldd /n/home08/xiey/.conda/envs/flaretest/lib/python3.8/site-packages/flare/bffs/sgp/_C_flare.so
        linux-vdso.so.1 =>  (0x00007fff89db0000)
        libstdc++.so.6 => /n/home08/xiey/.conda/envs/flaretest/lib/python3.8/site-packages/flare/bffs/sgp/../../../../../libstdc++.so.6 (0x00002b3977922000)
        libgcc_s.so.1 => /n/home08/xiey/.conda/envs/flaretest/lib/python3.8/site-packages/flare/bffs/sgp/../../../../../libgcc_s.so.1 (0x00002b397777d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b3977ad6000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b3977ea4000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b39776fe000)
```

I got exactly the same error of `undefined symbol: _ZTI6Kernel` after my conda installation, with the above .so file

**Comment by YuuuXie** [comment]
Hi @jan-janssen , I wonder if you know any other conda-forge packages with similar settings: i.e. they compile c++ lib linked with openblas/mkl, and then use the c++ lib in python. If so, we can take a look at them and see if we can learn from them

**Comment by jan-janssen** [comment]
@YuuuXie The part I do not understand is where `_ZTI6Kernel` symbol is defined. I would assume it is part of `eigen` but I can not find it there, so something goes wrong during the compilation. 

The line that makes me wonder is:
```
  -- Found LAPACK: /home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_intel_lp64.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_intel_thread.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_core.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libiomp5.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
  -- Linking Eigen to MKL.
```
You do not want to compile `eigen` again, you want to link to the library.

**Comment by jan-janssen** [comment]
@conda-forge/help-c-cpp

**Comment by YuuuXie** [comment]
> @YuuuXie The part I do not understand is where `_ZTI6Kernel` symbol is defined. I would assume it is part of `eigen` but I can not find it there, so something goes wrong during the compilation.
> 
> The line that makes me wonder is:
> 
> ```
>   -- Found LAPACK: /home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_intel_lp64.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_intel_thread.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libmkl_core.so;/home/conda/feedstock_root/build_artifacts/mir-flare_1667344477398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libiomp5.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
>   -- Linking Eigen to MKL.
> ```
> 
> You do not want to compile `eigen` again, you want to link to the library.

So the message of "Linking Eigen to MKL" comes from the cmake script below:
```cmake
  if (LAPACK_LIBRARIES MATCHES mkl)
    message(STATUS "Linking Eigen to MKL.")
    target_compile_definitions(flare PUBLIC EIGEN_USE_MKL_ALL=1)
  else()
```
where only a compilation flag is set, but since eigen is not downloaded it is not going to be compiled, so this flag will simply be useless and not concerning. Sorry about the confusion.

The `_ZTI6Kernel` I'm assuming is from lapack(e) but I can not find anything either...

**Comment by YuuuXie** [comment]
> @conda-forge/help-c-cpp

Hi @jan-janssen , does this command call for the conda forge cpp experts for help? Just wonder if we need to ask somebody since there is also the Gitter channel, but I don't have much experience with it. 

Thanks!

**Pull request closed without merging**
